/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Parse user input into standardized analysis parameters. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Free-text query (natural language input) */
                        query?: string;
                        /** @description Niche/topic keyword (structured input) */
                        niche?: string;
                        /** @enum {string} */
                        domain?: "SEO" | "content" | "ecommerce" | "saas" | "social";
                        /** @enum {string} */
                        effort_level?: "low" | "medium" | "high";
                        /** @description Budget in USD/month */
                        budget?: number;
                        /** @description Time horizon in months */
                        time_horizon?: number;
                        /** @enum {string} */
                        content_frequency?: "daily" | "weekly" | "biweekly" | "monthly";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            params: {
                                /** @enum {string} */
                                domain: "SEO" | "content" | "ecommerce" | "saas" | "social";
                                niche: string;
                                /** @enum {string} */
                                effort_level: "low" | "medium" | "high";
                                budget: number;
                                time_horizon: number;
                                /** @enum {string} */
                                content_frequency: "daily" | "weekly" | "biweekly" | "monthly";
                            };
                            /** @enum {string} */
                            parsed_from: "natural_language" | "structured_form";
                            confidence: number;
                            raw_query?: string;
                            needs_clarification: boolean;
                            clarification_prompt?: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit confirmed parameters to the worker for full analysis pipeline. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        niche: string;
                        /** @enum {string} */
                        domain: "SEO" | "content" | "ecommerce" | "saas" | "social";
                        /** @enum {string} */
                        effort_level?: "low" | "medium" | "high";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/status/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Check if a keyword has been fully scored. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/result/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get full feasibility report by keyword slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compare feasibility of multiple already-scored keywords by slug */
        get: {
            parameters: {
                query: {
                    /** @description Comma-separated list of keyword slugs (2-5) */
                    slugs: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            scenario_count: number;
                            tier: string;
                            comparison_table: {
                                index?: number;
                                label?: string;
                                feasibility_score?: number;
                                difficulty?: string;
                                demand_score?: number;
                                competition_score?: number;
                                constraint_pressure?: number;
                                regime?: string;
                                regime_adjustment?: number;
                                time_range?: string;
                                success_band?: {
                                    best_case?: number;
                                    expected?: number;
                                    worst_case?: number;
                                };
                                top_constraints?: string[];
                                conditions_count?: number;
                                composite_rank?: number;
                            }[];
                            recommendation: {
                                recommended_index?: null | number;
                                explanation?: string;
                            };
                            tradeoffs: {
                                index?: number;
                                label?: string;
                                advantages_over_recommended?: string[];
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** @description Compare multiple hypothetical scenarios side-by-side */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        scenarios: {
                            label: string;
                            niche: string;
                            /** @enum {string} */
                            domain?: "SEO" | "content" | "ecommerce" | "saas" | "social";
                            /** @enum {string} */
                            effort_level?: "low" | "medium" | "high";
                            budget?: number;
                            time_horizon?: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            scenario_count: number;
                            tier: string;
                            comparison_table: {
                                index?: number;
                                label?: string;
                                feasibility_score?: number;
                                difficulty?: string;
                                demand_score?: number;
                                competition_score?: number;
                                constraint_pressure?: number;
                                regime?: string;
                                regime_adjustment?: number;
                                time_range?: string;
                                success_band?: {
                                    best_case?: number;
                                    expected?: number;
                                    worst_case?: number;
                                };
                                top_constraints?: string[];
                                conditions_count?: number;
                                composite_rank?: number;
                            }[];
                            recommendation: {
                                recommended_index?: null | number;
                                explanation?: string;
                            };
                            tradeoffs: {
                                index?: number;
                                label?: string;
                                advantages_over_recommended?: string[];
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/niches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List recently analyzed niches */
        get: {
            parameters: {
                query?: {
                    domain?: "SEO" | "content" | "ecommerce" | "saas" | "social";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            niches: {
                                keyword?: string;
                                slug?: string;
                                domain?: string;
                                feasibility_score?: number;
                                difficulty?: string;
                                /** Format: date-time */
                                scored_at?: string;
                            }[];
                            total: number;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit outcome feedback for a scored keyword */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        keyword_slug: string;
                        actual_result: string;
                        months_elapsed?: number;
                        traffic_achieved?: number;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            outcome_id: number;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Export feasibility report as JSON */
        get: {
            parameters: {
                query?: {
                    format?: "json" | "csv";
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exported report data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
