/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit a niche/keyword for feasibility analysis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Search query or niche keyword */
                        query?: string;
                        /** @description Niche category */
                        niche?: string;
                        /** @enum {string} */
                        domain?: "SEO" | "content" | "ecommerce" | "saas" | "social";
                        /** @enum {string} */
                        effort_level?: "low" | "medium" | "high";
                        /** @description Budget in USD */
                        budget?: number;
                        /** @description Time horizon in months */
                        time_horizon?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            keyword: string;
                            slug: string;
                            /** @enum {string} */
                            domain: "SEO" | "content" | "ecommerce" | "saas" | "social";
                            feasibility_score: number;
                            demand_score: number;
                            competition_score: number;
                            constraint_pressure: number;
                            /** @enum {string} */
                            difficulty: "easy" | "medium" | "hard" | "very_hard";
                            time_range_min: number;
                            time_range_max: number;
                            /** @enum {string} */
                            regime: "emerging" | "trending" | "stable" | "saturated" | "declining";
                            success_band: {
                                best_case: number;
                                expected: number;
                                worst_case: number;
                            };
                            constraints: {
                                type: string;
                                /** @enum {string} */
                                severity: "high" | "medium" | "low";
                                /** @enum {string} */
                                category: "hard" | "soft";
                                description: string;
                                implication: string;
                            }[];
                            conditions: string[];
                            /** Format: date-time */
                            scored_at: string;
                        };
                    };
                };
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "processing" | "complete" | "failed";
                            job_id: string;
                            estimated_wait: string;
                            poll_url: string;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/result/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get feasibility result by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            keyword: string;
                            slug: string;
                            /** @enum {string} */
                            domain: "SEO" | "content" | "ecommerce" | "saas" | "social";
                            feasibility_score: number;
                            demand_score: number;
                            competition_score: number;
                            constraint_pressure: number;
                            /** @enum {string} */
                            difficulty: "easy" | "medium" | "hard" | "very_hard";
                            time_range_min: number;
                            time_range_max: number;
                            /** @enum {string} */
                            regime: "emerging" | "trending" | "stable" | "saturated" | "declining";
                            success_band: {
                                best_case: number;
                                expected: number;
                                worst_case: number;
                            };
                            constraints: {
                                type: string;
                                /** @enum {string} */
                                severity: "high" | "medium" | "low";
                                /** @enum {string} */
                                category: "hard" | "soft";
                                description: string;
                                implication: string;
                            }[];
                            conditions: string[];
                            /** Format: date-time */
                            scored_at: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compare feasibility of multiple niches */
        get: {
            parameters: {
                query: {
                    /** @description Comma-separated list of keyword slugs */
                    slugs: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: {
                                keyword: string;
                                slug: string;
                                /** @enum {string} */
                                domain: "SEO" | "content" | "ecommerce" | "saas" | "social";
                                feasibility_score: number;
                                demand_score: number;
                                competition_score: number;
                                constraint_pressure: number;
                                /** @enum {string} */
                                difficulty: "easy" | "medium" | "hard" | "very_hard";
                                time_range_min: number;
                                time_range_max: number;
                                /** @enum {string} */
                                regime: "emerging" | "trending" | "stable" | "saturated" | "declining";
                                success_band: {
                                    best_case: number;
                                    expected: number;
                                    worst_case: number;
                                };
                                constraints: {
                                    type: string;
                                    /** @enum {string} */
                                    severity: "high" | "medium" | "low";
                                    /** @enum {string} */
                                    category: "hard" | "soft";
                                    description: string;
                                    implication: string;
                                }[];
                                conditions: string[];
                                /** Format: date-time */
                                scored_at: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/niches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List recently analyzed niches */
        get: {
            parameters: {
                query?: {
                    domain?: "SEO" | "content" | "ecommerce" | "saas" | "social";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            niches: {
                                keyword?: string;
                                slug?: string;
                                domain?: string;
                                feasibility_score?: number;
                                difficulty?: string;
                                /** Format: date-time */
                                scored_at?: string;
                            }[];
                            total: number;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit outcome feedback for a scored keyword */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        keyword_slug: string;
                        actual_result: string;
                        months_elapsed?: number;
                        traffic_achieved?: number;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            outcome_id: number;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Export feasibility report as JSON */
        get: {
            parameters: {
                query?: {
                    format?: "json" | "csv";
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exported report data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
